In [1]:
# Loading packages
using SymPy, LinearAlgebra, Latexify

# Define the symbolic 16×16 G matrix for default "Star" Network

In [24]:

G = SymPy.Matrix([
    0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1;
    1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0;
    1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0;
    1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0;
    1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0;
    0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0;
    0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0;
    0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0;
    0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1;
    0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0;
    0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0;
    0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1;
    0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0;
    0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0;
    0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0;
    1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
])

16×16 Matrix{Int64}:
 0  1  1  1  1  0  0  0  0  0  0  0  0  0  0  1
 1  0  1  1  1  0  0  0  0  0  0  0  0  0  0  0
 1  1  0  1  1  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  0  1  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  1  1  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  0  1  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  1  0  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  1  1  0  1  0  0  0  0  0  1
 0  0  0  0  0  1  1  1  1  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  0
 0  0  0  0  0  0  0  0  0  0  1  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  1  1  0  1  1  0
 0  0  0  0  0  0  0  0  0  0  1  1  1  0  1  0
 0  0  0  0  0  0  0  0  0  0  1  1  1  1  0  0
 1  0  0  0  0  0  0  0  1  0  0  1  0  0  0  0

# Generate the Information Matrix $\Gamma$

In [25]:
#Define Symbols
@syms p q beta_l beta_h

#Define denominators
den1 = q*(1-p) + (1-q)*p # Denominator for Pll, Plh
den2 = q*p + (1 - q)*(1 - p) # Denominator for Phl, Phh

#Define each term
# Pll
term1_Pll = (q^2 * (1 - p)) / den1 * (beta_l / beta_h)
term2_Pll = (p * (1 - q)^2) / den1
Pll =term1_Pll + term2_Pll

# Plh
term1_Plh = ((1 - q) * p * q) / den1
term2_Plh = (q * (1 - q) * (1 - p)) / den1 * (beta_l / beta_h)
Plh = term1_Plh + term2_Plh

# Phl
term1_Phl = (q * p * (1 - q)) / den2
term2_Phl = ((1 - q) * (1 - p) * q) / den2 * (beta_l / beta_h)
Phl = term1_Phl + term2_Phl

# Phh
term1_Phh = (p * q^2) / den2
term2_Phh = ((1 - p) * (1 - q)^2) / den2 * (beta_l / beta_h)
Phh = term1_Phh + term2_Phh

# Build the full Γ matrix
Gamma = SymPy.Matrix([
    [Pll Plh];
    [Phl Phh]
])

# Display the matrix
println("Gamma matrix:")
display(Gamma)

2×2 Matrix{Sym{PyCall.PyObject}}:
       p*(1 - q)^2/(p*(1 - q) + q*(1 - p)) + beta_l*q^2*(1 - p)/(beta_h*(p*(1 - q) + q*(1 - p)))  …  p*q*(1 - q)/(p*(1 - q) + q*(1 - p)) + beta_l*q*(1 - p)*(1 - q)/(beta_h*(p*(1 - q) + q*(1 - p)))
 p*q*(1 - q)/(p*q + (1 - p)*(1 - q)) + beta_l*q*(1 - p)*(1 - q)/(beta_h*(p*q + (1 - p)*(1 - q)))           p*q^2/(p*q + (1 - p)*(1 - q)) + beta_l*(1 - p)*(1 - q)^2/(beta_h*(p*q + (1 - p)*(1 - q)))

Gamma matrix:


## Original $\Gamma$ with $p=1/2$

In [26]:

Gamma_at_p_half = subs.(Gamma, p => Sym(1)//2)
Gamma_at_p_half = simplify(Gamma_at_p_half)
display(Gamma_at_p_half)

2×2 Matrix{Sym{PyCall.PyObject}}:
       (1 - q)^2 + beta_l*q^2/beta_h  q*(1 - q) + beta_l*q*(1 - q)/beta_h
 q*(1 - q) + beta_l*q*(1 - q)/beta_h        q^2 + beta_l*(1 - q)^2/beta_h

### Diagonalization of $\Gamma$ with $p=1/2$

In [27]:
#Comput diagonalization of the matrix
eigen_data = eigen(Gamma_at_p_half)

A = eigen_data.vectors
A = simplify(A)
A_values = eigen_data.values
A_values = simplify(A_values)

2-element Vector{Sym{PyCall.PyObject}}:
 (beta_h + beta_l)*(2*q^2 - 2*q + 1)/(2*beta_h) - sqrt(4*beta_h^2*q^4 - 8*beta_h^2*q^3 + 8*beta_h^2*q^2 - 4*beta_h^2*q + beta_h^2 + 8*beta_h*beta_l*q^4 - 16*beta_h*beta_l*q^3 + 8*beta_h*beta_l*q - 2*beta_h*beta_l + 4*beta_l^2*q^4 - 8*beta_l^2*q^3 + 8*beta_l^2*q^2 - 4*beta_l^2*q + beta_l^2)/(2*beta_h)
 (beta_h + beta_l)*(2*q^2 - 2*q + 1)/(2*beta_h) + sqrt(4*beta_h^2*q^4 - 8*beta_h^2*q^3 + 8*beta_h^2*q^2 - 4*beta_h^2*q + beta_h^2 + 8*beta_h*beta_l*q^4 - 16*beta_h*beta_l*q^3 + 8*beta_h*beta_l*q - 2*beta_h*beta_l + 4*beta_l^2*q^4 - 8*beta_l^2*q^3 + 8*beta_l^2*q^2 - 4*beta_l^2*q + beta_l^2)/(2*beta_h)

## Original $\Gamma$ with $p=1/2, \beta_l=0.03, \beta_h=0.06$

In [28]:
# Create a substitution dictionary
subs_dict_2 = Dict(
    p => Sym(1)//2,
    beta_l => 0.03,
    beta_h => 0.06
)
Gamma3 = subs.(Gamma, Ref(subs_dict_2))
Gamma3 = simplify(Gamma3)
display(Gamma3)

2×2 Matrix{Sym{PyCall.PyObject}}:
 0.5*q^2 + (1 - q)^2        1.5*q*(1 - q)
       1.5*q*(1 - q)  q^2 + 0.5*(1 - q)^2

### Eigenvectors and its Inverse

In [29]:
eigen_data_3 = eigen(Gamma3)
A_1_vectors = eigen_data_3.vectors
a_11_gen = A_1_vectors[1, 1]
a_12_gen = A_1_vectors[1, 2]
a_21_gen = A_1_vectors[2, 1]
a_22_gen = A_1_vectors[2, 2]
A_1_vectors_inv = inv(A_1_vectors)
a_11_gen_inv = A_1_vectors_inv[1, 1]
a_12_gen_inv = A_1_vectors_inv[1, 2]
a_21_gen_inv = A_1_vectors_inv[2, 1]
a_22_gen_inv = A_1_vectors_inv[2, 2]

    /                                                                          >
    |                          /     4    3                      2             >
1.0*\0.117851130197758*q + 0.5*\0.5*q  - q  + 0.555555555555556*q  - 0.0555555 >

>                                  0.5                    \                    >
>                                 \                       | /     4    3       >
> 555555556*q + 0.0138888888888889/    - 0.058925565098879/*\0.5*q  - q  + 0.5 >

>                                                               -0.5
>                 2                                            \    
> 55555555555556*q  - 0.0555555555555556*q + 0.0138888888888889/    

In [30]:
println(A_1_vectors)

Sym{PyCall.PyObject}[(3.0*q^2 - 2.0*q + 1.0)/(3.0*q^2 - 3.0*q) - 2.0*(1.5*q^2 - 1.5*q - 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75)/(3.0*q^2 - 3.0*q) (3.0*q^2 - 2.0*q + 1.0)/(3.0*q^2 - 3.0*q) - 2.0*(1.5*q^2 - 1.5*q + 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75)/(3.0*q^2 - 3.0*q); 1.00000000000000 1.00000000000000]


### Eigenvalues

In [31]:
A_1_values = eigen_data_3.values

2-element Vector{Sym{PyCall.PyObject}}:
 1.5*q^2 - 1.5*q - 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75
 1.5*q^2 - 1.5*q + 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75

#### Retrieve each terms in eigenvalues

In [32]:
# retrieve each element of eigenvalues
lambda_1_gen = A_1_values[1]
println("lambda_1_gen: ", lambda_1_gen)
lambda_2_gen = A_1_values[2]
println("lambda_2_gen: ", lambda_2_gen)




lambda_1_gen: 1.5*q^2 - 1.5*q - 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75
lambda_2_gen: 1.5*q^2 - 1.5*q + 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75


### Check if b is increasing in q (temporarily disabled)

In [15]:
# Calculate b = (I - lambda * beta_h * G)^(-1)
#n=16
#beta_h = 0.2
#beta_l = 0.1
#I = SymPy.Matrix(LinearAlgebra.I, n, n)
# Define symbolic variable
#q = symbols("q", real=true)

# Copy the expression for lambda from the eigenvalues A_2 values
#lambda_1_gen_expr = 1.5*q^2 - 1.5*q - 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75
#lambda_2_gen_expr = 1.5*q^2 - 1.5*q + 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75
# Now loop over q values
#for test_q in [0.1,0.3, 0.5, 0.7, 0.9]
    
    # Substitute q into lambda_expr
    #λ_val_1 = SymPy.subs(lambda_1_gen_expr, q => test_q)
    #λ_val_2 = SymPy.subs(lambda_2_gen_expr, q => test_q)
    # Build A matrix
    #Total_l_star= a_11_gen * a_11_gen_inv * inv(I - λ_val_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a_12 * a_21_inv * inv(I - lambda_2 * E_beta_complete * G)* SymPy.ones(16, 1) + a_11 * a_12_inv * inv(I - lambda_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a_12 * a_22_inv * inv(I - lambda_2 * E_beta_complete * G) * SymPy.ones(16, 1)
    #x_star_groupleader = x_star[1]
    #x_star_members = x_star[2]
    #x_star_higherleader = x_star[16]

    #println("At q= $test_q, x_star_groupleader = $x_star_groupleader, x_star_members = $x_star_members, x_star_higherleader = $x_star_higherleader")
#end

## Original $\Gamma$ with $p=1/2,q=3/5,\beta_l=0.03,\beta_h=0.6$

In [33]:
# now we set q = 3/5 back to the original code
subs_dict_3 = Dict(
    q => Sym(3)//5,
    p => Sym(1)//2,
    beta_l => 0.03,
    beta_h => 0.06
)
Gamma4 = subs.(Gamma, Ref(subs_dict_3))
display(Gamma4)

2×2 Matrix{Sym{PyCall.PyObject}}:
 0.340000000000000  0.360000000000000
 0.360000000000000  0.440000000000000

### Eigenvectors and Eigenvalues

In [34]:
eigen_Gamma4 = eigen(Gamma4)
A_4_vectors = eigen_Gamma4.vectors
display(A_4_vectors)
A_4_values = eigen_Gamma4.values
display(A_4_values)

1×2 Matrix{Sym{PyCall.PyObject}}:
 Matrix([
[ 0.754177820966212],
[-0.656670247812901]])  …  Matrix([
[0.656670247812901],
[0.754177820966212]])

2-element Vector{Sym{PyCall.PyObject}}:
 0.0265443630922750
  0.753455636907725

#### Retrieve elemets

In [35]:
a_1=A_4_vectors[1,1]
if isa(a_1, Sym)
    a_1_list = a_1.tolist()   
    a_1_matrix = SymPy.Matrix(a_1_list) 
else
    a_1_matrix = a_1 
end

a_11 = a_1_matrix[1,1]
a_21 = a_1_matrix[2,1]

println(a_11)
println(a_21)


0.754177820966212
-0.656670247812901


In [36]:
a_2=A_4_vectors[1,2]
if isa(a_2, Sym)
    a_2_list = a_2.tolist()   # Convert to Julia Array
    a_2_matrix = SymPy.Matrix(a_2_list)  # Rebuild clean Matrix
else
    a_2_matrix = a_2  # Already clean
end

# Step 3: Access entries
a_12 = a_2_matrix[1,1]
a_22 = a_2_matrix[2,1]

println(a_12)
println(a_22)


0.656670247812901
0.754177820966212


In [37]:
A_4_vectors=SymPy.Matrix([
    a_11  a_12;
    a_21  a_22
])
A_4_vectors_inv = inv(A_4_vectors)
a_11_inv = A_4_vectors_inv[1,1]
a_12_inv = A_4_vectors_inv[1,2]
a_21_inv = A_4_vectors_inv[2,1]
a_22_inv = A_4_vectors_inv[2,2]
println(a_11_inv)
println(a_12_inv)
println(a_21_inv)
println(a_22_inv)

0.754177820966212
-0.656670247812901
0.656670247812901
0.754177820966212


### Calculate $b(\lambda_i(\Gamma),\beta_{max},G)$

#### Retrieve $\lambda$

In [38]:
lambda_1 = A_4_values[1]
lambda_2 = A_4_values[2]
println(lambda_1)
println(lambda_2)

0.0265443630922750
0.753455636907725


#### Generate G matrix for the Complete Network 

In [39]:
G_array = [i != j ? Sym(1) : Sym(0) for i in 1:16, j in 1:16]
G_complete = SymPy.Matrix(G_array)

16×16 Matrix{Sym{PyCall.PyObject}}:
 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  0  1  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  0  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  0  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  0  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  0  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  0  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  0  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  0  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  0  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  0  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  0  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  0  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0

#### Find $E[\beta]\leq 1/\lambda_{max}$

In [40]:
G_complete_eign = eigen(G_complete)
G_complete_eigenvalues = G_complete_eign.values
# Retrieve the max eigenvalue
max_eigenvalue = maximum(G_complete_eigenvalues)
E_beta_complete = 1/max_eigenvalue

1/15

## x_star for l for default network

In [61]:
Total_l_star= a_11 * a_11_inv * inv(I - lambda_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a_12 * a_21_inv * inv(I - lambda_2 * E_beta_complete * G)* SymPy.ones(16, 1) + a_11 * a_12_inv * inv(I - lambda_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a_12 * a_22_inv * inv(I - lambda_2 * E_beta_complete * G) * SymPy.ones(16, 1)

16×1 Matrix{Sym{PyCall.PyObject}}:
 1.29001581741974
 1.23681169522142
 1.23681169522142
 1.23681169522142
 1.23681169522142
 1.23681169522142
 1.23681169522142
 1.23681169522142
 1.29001581741974
 1.23681169522142
 1.23681169522142
 1.29001581741974
 1.23681169522142
 1.23681169522142
 1.23681169522142
 1.18360757302310

## x_star for h for default network

In [74]:
Total_h_star= a_21 * a_11_inv * inv(I - lambda_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a_22 * a_21_inv * inv(I - lambda_2 * E_beta_complete * G)* SymPy.ones(16, 1) + a_21 * a_12_inv * inv(I - lambda_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a_22 * a_22_inv * inv(I - lambda_2 * E_beta_complete * G) * SymPy.ones(16, 1)

16×1 Matrix{Sym{PyCall.PyObject}}:
 1.33175690886891
 1.27091632785180
 1.27091632785180
 1.27091632785180
 1.27091632785180
 1.27091632785180
 1.27091632785180
 1.27091632785180
 1.33175690886891
 1.27091632785180
 1.27091632785180
 1.33175690886891
 1.27091632785180
 1.27091632785180
 1.27091632785180
 1.21007574683468

### Summary of Coefficient

In [77]:
println("Total Welfare in default network")
println("| Type | Group Leader | Member | Higher Leader |")
println("|-----|--------------|--------|---------------|")
println("| l   | $(Total_l_star[1]) | $(Total_l_star[2]) | $(Total_l_star[16]) |")
println("| h   | $(Total_h_star[1]) | $(Total_h_star[2]) | $(Total_h_star[16]) |")


Total Welfare in default network
| Type | Group Leader | Member | Higher Leader |
|-----|--------------|--------|---------------|
| l   | 1.29001581741974 | 1.23681169522142 | 1.18360757302310 |
| h   | 1.33175690886891 | 1.27091632785180 | 1.21007574683468 |


## x_star in complete network

### l type

In [62]:
Total_l_complete= a_11 * a_11_inv * inv(I - lambda_1 * E_beta_complete * G_complete)* SymPy.ones(16, 1) + a_12 * a_21_inv * inv(I - lambda_2 * E_beta_complete * G_complete)* SymPy.ones(16, 1) + a_11 * a_12_inv * inv(I - lambda_1 * E_beta_complete * G_complete)* SymPy.ones(16, 1) + a_12 * a_22_inv * inv(I - lambda_2 * E_beta_complete * G_complete) * SymPy.ones(16, 1)

16×1 Matrix{Sym{PyCall.PyObject}}:
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333
 3.83333333333333

### h type

In [75]:
Total_h_complete= a_21 * a_11_inv * inv(I - lambda_1 * E_beta_complete * G_complete)* SymPy.ones(16, 1) + a_22 * a_21_inv * inv(I - lambda_2 * E_beta_complete * G_complete)* SymPy.ones(16, 1) + a_21 * a_12_inv * inv(I - lambda_1 * E_beta_complete * G_complete)* SymPy.ones(16, 1) + a_22 * a_22_inv * inv(I - lambda_2 * E_beta_complete * G_complete) * SymPy.ones(16, 1)

16×1 Matrix{Sym{PyCall.PyObject}}:
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000
 4.25000000000000

In [76]:
println("Total Welfare in complete network")
println("| Type | Group Leader | Member | Higher Leader |")
println("|-----|--------------|--------|---------------|")
println("| l   | $(Total_l_complete[1]) | $(Total_l_complete[2]) | $(Total_l_complete[16]) |")
println("| h   | $(Total_h_complete[1]) | $(Total_h_complete[2]) | $(Total_h_complete[16]) |")

Total Welfare in complete network
| Type | Group Leader | Member | Higher Leader |
|-----|--------------|--------|---------------|
| l   | 3.83333333333333 | 3.83333333333333 | 3.83333333333333 |
| h   | 4.25000000000000 | 4.25000000000000 | 4.25000000000000 |


## Natural disaster shock in productivity

In [ ]:
# Suppose normally we have \alpha=0.9, natural disaster decerase it to 0.5
alpha_natural = 0.9
alpha_natural_disaster = 0.5


# check how a* performs in q

In [107]:
println(a_11_gen)
println(a_12_gen)
println(a_21_gen)
println(a_22_gen)
println(a_11_gen_inv)
println(a_12_gen_inv)
println(a_21_gen_inv)
println(a_22_gen_inv)

(3.0*q^2 - 2.0*q + 1.0)/(3.0*q^2 - 3.0*q) - 2.0*(1.5*q^2 - 1.5*q - 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75)/(3.0*q^2 - 3.0*q)
(3.0*q^2 - 2.0*q + 1.0)/(3.0*q^2 - 3.0*q) - 2.0*(1.5*q^2 - 1.5*q + 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75)/(3.0*q^2 - 3.0*q)
1.00000000000000
1.00000000000000
1.0*(0.353553390593274*q^2 - 0.353553390593274*q)/(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5
1.0*(-0.117851130197758*q + 0.5*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.058925565098879)/(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5
1.0*(-0.353553390593274*q^2 + 0.353553390593274*q)/(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5
1.0*(0.117851130197758*q + 0.5*(0.5*q^4 - q^3 + 0.55555555555555

In [130]:
n=16
beta_h = 0.2
beta_l = 0.1
I_sym = SymPy.sympy.eye(n)
# Define symbolic variable
q = symbols("q", real=true)

# Copy the expression for lambda from the eigenvalues A_2 values
lambda_1_gen_expr = 1.5*q^2 - 1.5*q - 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75
lambda_2_gen_expr = 1.5*q^2 - 1.5*q + 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75
a_11_expr = (3.0*q^2 - 2.0*q + 1.0)/(3.0*q^2 - 3.0*q) - 2.0*(1.5*q^2 - 1.5*q - 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75)/(3.0*q^2 - 3.0*q)
a_12_expr = (3.0*q^2 - 2.0*q + 1.0)/(3.0*q^2 - 3.0*q) - 2.0*(1.5*q^2 - 1.5*q + 2.12132034355964*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.75)/(3.0*q^2 - 3.0*q)
a_11_inv_expr = 1.0*(0.353553390593274*q^2 - 0.353553390593274*q)/(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5
a_12_inv_expr = 1.0*(-0.117851130197758*q + 0.5*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 + 0.058925565098879)/(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5
a_21_inv_expr = 1.0*(-0.353553390593274*q^2 + 0.353553390593274*q)/(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5
a_22_inv_expr = 1.0*(0.117851130197758*q + 0.5*(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5 - 0.058925565098879)/(0.5*q^4 - q^3 + 0.555555555555556*q^2 - 0.0555555555555556*q + 0.0138888888888889)^0.5


/                                                                              >
|                          /     4    3                      2                 >
\0.117851130197758*q + 0.5*\0.5*q  - q  + 0.555555555555556*q  - 0.05555555555 >

>                              0.5                    \                        >
>                             \                       | /     4    3           >
> 55556*q + 0.0138888888888889/    - 0.058925565098879/*\0.5*q  - q  + 0.55555 >

>                                                           -0.5
>             2                                            \    
> 5555555556*q  - 0.0555555555555556*q + 0.0138888888888889/    

## test for l type in default network

In [136]:
for test_q in [0.1,0.3, 0.5, 0.7, 0.9]
    
    # Substitute q into lambda_expr
    λ_val_1 = SymPy.subs(lambda_1_gen_expr, q => test_q)
    λ_val_2 = SymPy.subs(lambda_2_gen_expr, q => test_q)
    a11 = SymPy.subs(a_11_expr, q => test_q)
    a12 = SymPy.subs(a_12_expr, q => test_q)
    a11_inv = SymPy.subs(a_11_inv_expr, q => test_q)
    a12_inv = SymPy.subs(a_12_inv_expr, q => test_q)
    a21_inv = SymPy.subs(a_21_inv_expr, q => test_q)
    a22_inv = SymPy.subs(a_22_inv_expr, q => test_q)
    # Build A matrix
    Total_l_star_gen= a11 * a11_inv * inv(I - λ_val_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a12 * a21_inv * inv(I - λ_val_2 * E_beta_complete * G)* SymPy.ones(16, 1) + a11 * a12_inv * inv(I - λ_val_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a12 * a22_inv * inv(I - λ_val_2 * E_beta_complete * G) * SymPy.ones(16, 1)
    x_star_groupleader = Total_l_star_gen[1]
    x_star_members = Total_l_star_gen[2]
    x_star_higherleader = Total_l_star_gen[16]

    println("At q= $test_q, x_star_groupleader = $x_star_groupleader, x_star_members = $x_star_members, x_star_higherleader = $x_star_higherleader")
end

At q= 0.1, x_star_groupleader = 1.41210111014765, x_star_members = 1.33762981239169, x_star_higherleader = 1.26315851463572
At q= 0.3, x_star_groupleader = 1.35474385053318, x_star_members = 1.28982971522787, x_star_higherleader = 1.22491557992255
At q= 0.5, x_star_groupleader = 1.31054131054131, x_star_members = 1.25356125356125, x_star_higherleader = 1.19658119658120
At q= 0.7, x_star_groupleader = 1.26917441135715, x_star_members = 1.21977897975084, x_star_higherleader = 1.17038354814452
At q= 0.9, x_star_groupleader = 1.22170495117251, x_star_members = 1.18061659604691, x_star_higherleader = 1.13952824092131


## test for h type in default network

In [143]:
for test_q in [0.1,0.3, 0.5, 0.7, 0.9]
    
    # Substitute q into lambda_expr
    λ_val_1 = SymPy.subs(lambda_1_gen_expr, q => test_q)
    λ_val_2 = SymPy.subs(lambda_2_gen_expr, q => test_q)
    a11 = SymPy.subs(a_11_expr, q => test_q)
    a12 = SymPy.subs(a_12_expr, q => test_q)
    a11_inv = SymPy.subs(a_11_inv_expr, q => test_q)
    a12_inv = SymPy.subs(a_12_inv_expr, q => test_q)
    a21_inv = SymPy.subs(a_21_inv_expr, q => test_q)
    a22_inv = SymPy.subs(a_22_inv_expr, q => test_q)
    # Build A matrix
    Total_h_star_gen= a_21_gen * a11_inv * inv(I - λ_val_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a_22_gen * a21_inv * inv(I - λ_val_2 * E_beta_complete * G)* SymPy.ones(16, 1) + a_21_gen * a12_inv * inv(I - λ_val_1 * E_beta_complete * G)* SymPy.ones(16, 1) + a_22_gen * a22_inv * inv(I - λ_val_2 * E_beta_complete * G) * SymPy.ones(16, 1)
    x_star_groupleader = Total_h_star_gen[1]
    x_star_members = Total_h_star_gen[2]
    x_star_higherleader = Total_h_star_gen[16]

    println("At q= $test_q, x_star_groupleader = $x_star_groupleader, x_star_members = $x_star_members, x_star_higherleader = $x_star_higherleader")
end

At q= 0.1, x_star_groupleader = 1.22170495117250, x_star_members = 1.18061659604690, x_star_higherleader = 1.13952824092130
At q= 0.3, x_star_groupleader = 1.26917441135715, x_star_members = 1.21977897975083, x_star_higherleader = 1.17038354814452
At q= 0.5, x_star_groupleader = 1.31054131054131, x_star_members = 1.25356125356125, x_star_higherleader = 1.19658119658120
At q= 0.7, x_star_groupleader = 1.35474385053319, x_star_members = 1.28982971522787, x_star_higherleader = 1.22491557992255
At q= 0.9, x_star_groupleader = 1.41210111014765, x_star_members = 1.33762981239169, x_star_higherleader = 1.26315851463572
