In [1]:
#loading packages
using SymPy
using LinearAlgebra

# Define symbolic variables

In [2]:

p = symbols("p", real=true)
beta_low = symbols("beta_l", real=true)
beta_high = symbols("beta_h", real=true)
α = symbols("alpha", real=true)

alpha

# Define expected beta symbolically

In [3]:

E_beta = p * beta_high + (1 - p) * beta_low

beta_h*p + beta_l*(1 - p)

# Define the symbolic 16×16 G matrix for default network

In [4]:

G = SymPy.Matrix([
    0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1;
    1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0;
    1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0;
    1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0;
    1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0;
    0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0;
    0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0;
    0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0;
    0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1;
    0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0;
    0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0;
    0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1;
    0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0;
    0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0;
    0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0;
    1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
])

16×16 Matrix{Int64}:
 0  1  1  1  1  0  0  0  0  0  0  0  0  0  0  1
 1  0  1  1  1  0  0  0  0  0  0  0  0  0  0  0
 1  1  0  1  1  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  0  1  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  1  1  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  0  1  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  1  0  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  1  1  0  1  0  0  0  0  0  1
 0  0  0  0  0  1  1  1  1  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  0
 0  0  0  0  0  0  0  0  0  0  1  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  1  1  0  1  1  0
 0  0  0  0  0  0  0  0  0  0  1  1  1  0  1  0
 0  0  0  0  0  0  0  0  0  0  1  1  1  1  0  0
 1  0  0  0  0  0  0  0  1  0  0  1  0  0  0  0

# Calculation of $x^*$

## Build the matrix $A = I - E[\beta] \times G$

In [5]:
n = 16
I = SymPy.Matrix(LinearAlgebra.I, n, n)
A = I - E_beta * G

16×16 Matrix{Sym{PyCall.PyObject}}:
                          1  …  -beta_h*p - beta_l*(1 - p)
 -beta_h*p - beta_l*(1 - p)                              0
 -beta_h*p - beta_l*(1 - p)                              0
 -beta_h*p - beta_l*(1 - p)                              0
 -beta_h*p - beta_l*(1 - p)                              0
                          0  …                           0
                          0                              0
                          0                              0
                          0     -beta_h*p - beta_l*(1 - p)
                          0                              0
                          0  …                           0
                          0     -beta_h*p - beta_l*(1 - p)
                          0                              0
                          0                              0
                          0                              0
 -beta_h*p - beta_l*(1 - p)  …                           1

## Suppose p=0.5

In [6]:
A_1 = subs.(A, p => Sym(1)//2)

16×16 Matrix{Sym{PyCall.PyObject}}:
                    1  -beta_h/2 - beta_l/2  …  -beta_h/2 - beta_l/2
 -beta_h/2 - beta_l/2                     1                        0
 -beta_h/2 - beta_l/2  -beta_h/2 - beta_l/2                        0
 -beta_h/2 - beta_l/2  -beta_h/2 - beta_l/2                        0
 -beta_h/2 - beta_l/2  -beta_h/2 - beta_l/2                        0
                    0                     0  …                     0
                    0                     0                        0
                    0                     0                        0
                    0                     0     -beta_h/2 - beta_l/2
                    0                     0                        0
                    0                     0  …                     0
                    0                     0     -beta_h/2 - beta_l/2
                    0                     0                        0
                    0                     0                        

### Inverse A_1

In [7]:
A_1_inv = A_1.inv()

16×16 Matrix{Sym{PyCall.PyObject}}:
 (18*beta_h^4 + 72*beta_h^3*beta_l - 48*beta_h^3 + 108*beta_h^2*beta_l^2 - 144*beta_h^2*beta_l - 12*beta_h^2 + 72*beta_h*beta_l^3 - 144*beta_h*beta_l^2 - 24*beta_h*beta_l + 48*beta_h + 18*beta_l^4 - 48*beta_l^3 - 12*beta_l^2 + 48*beta_l - 16)/(18*beta_h^5 + 90*beta_h^4*beta_l - beta_h^4 + 180*beta_h^3*beta_l^2 - 4*beta_h^3*beta_l - 84*beta_h^3 + 180*beta_h^2*beta_l^3 - 6*beta_h^2*beta_l^2 - 252*beta_h^2*beta_l + 8*beta_h^2 + 90*beta_h*beta_l^4 - 4*beta_h*beta_l^3 - 252*beta_h*beta_l^2 + 16*beta_h*beta_l + 48*beta_h + 18*beta_l^5 - beta_l^4 - 84*beta_l^3 + 8*beta_l^2 + 48*beta_l - 16)  …        (-6*beta_h^2 - 12*beta_h*beta_l + 4*beta_h - 6*beta_l^2 + 4*beta_l)/(9*beta_h^3 + 27*beta_h^2*beta_l - 14*beta_h^2 + 27*beta_h*beta_l^2 - 28*beta_h*beta_l - 12*beta_h + 9*beta_l^3 - 14*beta_l^2 - 12*beta_l + 8)
            (-6*beta_h^4 - 24*beta_h^3*beta_l + 12*beta_h^3 - 36*beta_h^2*beta_l^2 + 36*beta_h^2*beta_l + 12*beta_h^2 - 24*beta_h*beta_l^3 + 36*beta_h*b

### Calculation of $E[\beta] \leq \frac{1}{\lambda_{max}(G)}$

#### Calculate $\lambda(G)$

In [8]:
eigen_G = eigen(G)
eigenvalues_G = eigen_G.values 

16-element Vector{Float64}:
 -2.1622776601683755
 -1.0000000000000007
 -1.0000000000000004
 -1.0000000000000002
 -1.0
 -1.0
 -1.0
 -0.9999999999999998
 -0.9999999999999996
 -0.9999999999999993
 -0.9999999999999991
 -0.9999999999999973
  1.0000000000000022
  3.9999999999999916
  4.0
  4.16227766016838

#### Retrieve the maximum eigenvalue

In [9]:

lambda_max = maximum(eigenvalues_G)

4.16227766016838

#### Plug in $E[\beta] = \frac{1}{\lambda_{max}(G)}$

In [10]:

E_beta_2 = 1/lambda_max



0.2402530733520421

### Caculation of A when p=0.5

In [11]:
A_2 = I - E_beta_2 * G

16×16 Matrix{Float64}:
  1.0       -0.240253  -0.240253  …   0.0        0.0       -0.240253
 -0.240253   1.0       -0.240253      0.0        0.0        0.0
 -0.240253  -0.240253   1.0           0.0        0.0        0.0
 -0.240253  -0.240253  -0.240253      0.0        0.0        0.0
 -0.240253  -0.240253  -0.240253      0.0        0.0        0.0
  0.0        0.0        0.0       …   0.0        0.0        0.0
  0.0        0.0        0.0           0.0        0.0        0.0
  0.0        0.0        0.0           0.0        0.0        0.0
  0.0        0.0        0.0           0.0        0.0       -0.240253
  0.0        0.0        0.0           0.0        0.0        0.0
  0.0        0.0        0.0       …  -0.240253  -0.240253   0.0
  0.0        0.0        0.0          -0.240253  -0.240253  -0.240253
  0.0        0.0        0.0          -0.240253  -0.240253   0.0
  0.0        0.0        0.0           1.0       -0.240253   0.0
  0.0        0.0        0.0          -0.240253   1.0        0.0
 -

### then inverse A_2 to find x^*

In [12]:

A_2_inv = inv(A_2)


16×16 Matrix{Float64}:
 -1.87416e15  -1.61249e15  -1.61249e15  …  -1.61249e15  -1.35082e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15  …  -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.87416e15  -1.61249e15  -1.61249e15     -1.61249e15  -1.35082e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15  …  -1.38736e15  -1.16222e15
 -1.87416e15  -1.61249e15  -1.61249e15     -1.61249e15  -1.35082e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15

## Trying smaller beta

###  Start with $E[\beta]=0.2$

In [13]:

E_beta_3 = 0.2
E_beta_3_G = E_beta_3 * G
A_3 = I - E_beta_3_G
# then inverse A_3 to find x^*
A_3_inv = inv(A_3)

16×16 Matrix{Float64}:
 1.80556    0.902778   0.902778   …  0.0694444  0.0694444  0.416667
 0.902778   1.70139    0.868056      0.0347222  0.0347222  0.208333
 0.902778   0.868056   1.70139       0.0347222  0.0347222  0.208333
 0.902778   0.868056   0.868056      0.0347222  0.0347222  0.208333
 0.902778   0.868056   0.868056      0.0347222  0.0347222  0.208333
 0.0694444  0.0347222  0.0347222  …  0.0347222  0.0347222  0.208333
 0.0694444  0.0347222  0.0347222     0.0347222  0.0347222  0.208333
 0.0694444  0.0347222  0.0347222     0.0347222  0.0347222  0.208333
 0.138889   0.0694444  0.0694444     0.0694444  0.0694444  0.416667
 0.0694444  0.0347222  0.0347222     0.0347222  0.0347222  0.208333
 0.0694444  0.0347222  0.0347222  …  0.868056   0.868056   0.208333
 0.138889   0.0694444  0.0694444     0.902778   0.902778   0.416667
 0.0694444  0.0347222  0.0347222     0.868056   0.868056   0.208333
 0.0694444  0.0347222  0.0347222     1.70139    0.868056   0.208333
 0.0694444  0.0347222  0.

###  Then with $E[\beta]=0.1$

In [14]:
E_beta_3_2 = 0.1
A_3_2 = I - E_beta_3_2 * G
# then inverse A_3 to find x^*
A_3_2_inv = inv(A_3_2)

16×16 Matrix{Float64}:
 1.07222     0.153175     0.153175     …  0.00165979   0.00165979   0.109546
 0.153175    1.06084      0.151752        0.000237113  0.000237113  0.0156495
 0.153175    0.151752     1.06084         0.000237113  0.000237113  0.0156495
 0.153175    0.151752     0.151752        0.000237113  0.000237113  0.0156495
 0.153175    0.151752     0.151752        0.000237113  0.000237113  0.0156495
 0.00165979  0.000237113  0.000237113  …  0.000237113  0.000237113  0.0156495
 0.00165979  0.000237113  0.000237113     0.000237113  0.000237113  0.0156495
 0.00165979  0.000237113  0.000237113     0.000237113  0.000237113  0.0156495
 0.0116185   0.00165979   0.00165979      0.00165979   0.00165979   0.109546
 0.00165979  0.000237113  0.000237113     0.000237113  0.000237113  0.0156495
 0.00165979  0.000237113  0.000237113  …  0.151752     0.151752     0.0156495
 0.0116185   0.00165979   0.00165979      0.153175     0.153175     0.109546
 0.00165979  0.000237113  0.000237113     0.

## Investigate how $x^*$ performs in $p$

### Firstly with $\beta_l=0.03$, $\beta_h=0.06$

In [11]:

E_beta_4 =  0.06 * p + 0.03 * (1 - p)
E_beta_4_G = E_beta_4 * G
A_4 = I - E_beta_4_G
# then inverse A_4 to find x^*
A_4_inv = inv(A_4)
# then we can compute x^* = A^{-1} * 1
x_star_4 = A_4_inv * SymPy.ones(16, 1)

16×1 Matrix{Sym{PyCall.PyObject}}:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1.0*(-6.88747536e-22*p^15 - 2.4374010024e-19*p^14 - 3.859052444208e-17*p^13 - 3.58342528875408e-15*p^12 - 2.14285183614667e-1

#### Retrieve the three types of $x^*$

In [12]:

# x_star for group leader
x_star_4_leader = x_star_4[1]


               /                  15                     14                    >
           1.0*\- 6.88747536e-22*p   - 2.4374010024e-19*p   - 3.859052444208e- >
------------------------------------------------------------------------------ >
                 16                       15                        14         >
6.198727824e-23*p   + 2.108026625184e-20*p   + 3.1369350900888e-18*p   + 2.627 >

>     13                         12                         11                 >
> 17*p   - 3.58342528875408e-15*p   - 2.14285183614667e-13*p   - 8.47092656516 >
> ---------------------------------------------------------------------------- >
>                  13                         12                         11    >
> 11543980614e-16*p   + 1.29427598098481e-14*p   + 3.18538085457479e-13*p   -  >

>          10                         9                        8               >
> 252e-12*p   - 2.14634789411868e-10*p  - 2.96983680753851e-9*p  - 2.546211802 >
> ------------------------

In [13]:
# testing with specific values
for test_p in [0.1, 0.5, 0.9]
    val = subs(x_star_4_leader, Dict(p => test_p))
    println("x_star for leader at p = $test_p : ", val)
end

x_star for leader at p = 0.1 : 1.18913783719740
x_star for leader at p = 0.5 : 1.27274256398755
x_star for leader at p = 0.9 : 1.36677875575278


In [14]:
# testing for group members
x_star_4_member = x_star_4[2]
# find its derivative respect to p
# testing with specific values
for test_p in [0.1, 0.5, 0.9]
    val = subs(x_star_4_member, Dict(p => test_p))
    println("x_star for member at p = $test_p : ", val)
end


x_star for member at p = 0.1 : 1.15343124153997
x_star for member at p = 0.5 : 1.22228140506294
x_star for member at p = 0.9 : 1.30024896149325


In [15]:
# testing for higher level government
x_star_4_government = x_star_4[16]
# find its derivative respect to p
# testing with specific values
for test_p in [0.1, 0.5, 0.9]
    val = subs(x_star_4_government, Dict(p => test_p))
    println("x_star for government at p = $test_p : ", val)
end

x_star for government at p = 0.1 : 1.11772464588254
x_star for government at p = 0.5 : 1.17182024613832
x_star for government at p = 0.9 : 1.23371916723373
