In [1]:
#loading packages
using SymPy
using LinearAlgebra

In [2]:
# Define symbolic variables
p = symbols("p", real=true)
beta_low = symbols("beta_l", real=true)
beta_high = symbols("beta_h", real=true)
α = symbols("alpha", real=true)

alpha

In [3]:
# Define expected beta symbolically
E_beta = p * beta_high + (1 - p) * beta_low

beta_h*p + beta_l*(1 - p)

In [4]:
# Define the symbolic 16×16 G matrix
G = SymPy.Matrix([
    0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1;
    1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0;
    1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0;
    1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0;
    1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0;
    0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0;
    0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0;
    0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0;
    0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1;
    0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0;
    0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0;
    0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1;
    0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0;
    0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0;
    0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0;
    1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
])

16×16 Matrix{Int64}:
 0  1  1  1  1  0  0  0  0  0  0  0  0  0  0  1
 1  0  1  1  1  0  0  0  0  0  0  0  0  0  0  0
 1  1  0  1  1  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  0  1  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  1  1  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  0  1  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  1  0  1  1  0  0  0  0  0  0
 0  0  0  0  0  1  1  1  0  1  0  0  0  0  0  1
 0  0  0  0  0  1  1  1  1  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  0
 0  0  0  0  0  0  0  0  0  0  1  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  1  1  0  1  1  0
 0  0  0  0  0  0  0  0  0  0  1  1  1  0  1  0
 0  0  0  0  0  0  0  0  0  0  1  1  1  1  0  0
 1  0  0  0  0  0  0  0  1  0  0  1  0  0  0  0

In [5]:
# Build the matrix A = I - E_beta * G
n = 16
I = SymPy.Matrix(LinearAlgebra.I, n, n)
A = I - E_beta * G

16×16 Matrix{Sym{PyCall.PyObject}}:
                          1  …  -beta_h*p - beta_l*(1 - p)
 -beta_h*p - beta_l*(1 - p)                              0
 -beta_h*p - beta_l*(1 - p)                              0
 -beta_h*p - beta_l*(1 - p)                              0
 -beta_h*p - beta_l*(1 - p)                              0
                          0  …                           0
                          0                              0
                          0                              0
                          0     -beta_h*p - beta_l*(1 - p)
                          0                              0
                          0  …                           0
                          0     -beta_h*p - beta_l*(1 - p)
                          0                              0
                          0                              0
                          0                              0
 -beta_h*p - beta_l*(1 - p)  …                           1

In [6]:
# suppose p=0.5
A_1 = subs.(A, p => Sym(1)//2)

16×16 Matrix{Sym{PyCall.PyObject}}:
                    1  -beta_h/2 - beta_l/2  …  -beta_h/2 - beta_l/2
 -beta_h/2 - beta_l/2                     1                        0
 -beta_h/2 - beta_l/2  -beta_h/2 - beta_l/2                        0
 -beta_h/2 - beta_l/2  -beta_h/2 - beta_l/2                        0
 -beta_h/2 - beta_l/2  -beta_h/2 - beta_l/2                        0
                    0                     0  …                     0
                    0                     0                        0
                    0                     0                        0
                    0                     0     -beta_h/2 - beta_l/2
                    0                     0                        0
                    0                     0  …                     0
                    0                     0     -beta_h/2 - beta_l/2
                    0                     0                        0
                    0                     0                        

In [12]:
#Then inverse A_1
A_1_inv = A_1.inv()

16×16 Matrix{Sym{PyCall.PyObject}}:
 (18*beta_h^4 + 72*beta_h^3*beta_l - 48*beta_h^3 + 108*beta_h^2*beta_l^2 - 144*beta_h^2*beta_l - 12*beta_h^2 + 72*beta_h*beta_l^3 - 144*beta_h*beta_l^2 - 24*beta_h*beta_l + 48*beta_h + 18*beta_l^4 - 48*beta_l^3 - 12*beta_l^2 + 48*beta_l - 16)/(18*beta_h^5 + 90*beta_h^4*beta_l - beta_h^4 + 180*beta_h^3*beta_l^2 - 4*beta_h^3*beta_l - 84*beta_h^3 + 180*beta_h^2*beta_l^3 - 6*beta_h^2*beta_l^2 - 252*beta_h^2*beta_l + 8*beta_h^2 + 90*beta_h*beta_l^4 - 4*beta_h*beta_l^3 - 252*beta_h*beta_l^2 + 16*beta_h*beta_l + 48*beta_h + 18*beta_l^5 - beta_l^4 - 84*beta_l^3 + 8*beta_l^2 + 48*beta_l - 16)  …        (-6*beta_h^2 - 12*beta_h*beta_l + 4*beta_h - 6*beta_l^2 + 4*beta_l)/(9*beta_h^3 + 27*beta_h^2*beta_l - 14*beta_h^2 + 27*beta_h*beta_l^2 - 28*beta_h*beta_l - 12*beta_h + 9*beta_l^3 - 14*beta_l^2 - 12*beta_l + 8)
            (-6*beta_h^4 - 24*beta_h^3*beta_l + 12*beta_h^3 - 36*beta_h^2*beta_l^2 + 36*beta_h^2*beta_l + 12*beta_h^2 - 24*beta_h*beta_l^3 + 36*beta_h*b

In [ ]:
# Special cases where we plug in E[beta] with 1/lambda_max(G)
# Firstly we need to find the eigenvalues of G
eigen_G = eigen(G)
eigenvalues_G = eigen_G.values 

16-element Vector{Float64}:
 -2.1622776601683755
 -1.0000000000000007
 -1.0000000000000004
 -1.0
 -0.9999999999999998
 -0.9999999999999998
 -0.9999999999999998
 -0.9999999999999997
 -0.9999999999999996
 -0.9999999999999996
 -0.9999999999999993
 -0.9999999999999956
  1.0000000000000018
  3.999999999999988
  3.999999999999999
  4.162277660168379

In [8]:
#Retrieve the maximum eigenvalue
lambda_max = maximum(eigenvalues_G)

4.162277660168379

In [16]:
# Plug in E[beta] = 1/lambda_max(G)
E_beta_2 = 1/lambda_max
E_beta_2_G = E_beta_2 * G


16×16 Matrix{Float64}:
 0.0       0.240253  0.240253  0.240253  …  0.0       0.0       0.240253
 0.240253  0.0       0.240253  0.240253     0.0       0.0       0.0
 0.240253  0.240253  0.0       0.240253     0.0       0.0       0.0
 0.240253  0.240253  0.240253  0.0          0.0       0.0       0.0
 0.240253  0.240253  0.240253  0.240253     0.0       0.0       0.0
 0.0       0.0       0.0       0.0       …  0.0       0.0       0.0
 0.0       0.0       0.0       0.0          0.0       0.0       0.0
 0.0       0.0       0.0       0.0          0.0       0.0       0.0
 0.0       0.0       0.0       0.0          0.0       0.0       0.240253
 0.0       0.0       0.0       0.0          0.0       0.0       0.0
 0.0       0.0       0.0       0.0       …  0.240253  0.240253  0.0
 0.0       0.0       0.0       0.0          0.240253  0.240253  0.240253
 0.0       0.0       0.0       0.0          0.240253  0.240253  0.0
 0.0       0.0       0.0       0.0          0.0       0.240253  0.0
 0.0      

In [17]:
A_2 = I - E_beta_2_G

16×16 Matrix{Float64}:
  1.0       -0.240253  -0.240253  …  -0.0       -0.0       -0.240253
 -0.240253   1.0       -0.240253     -0.0       -0.0       -0.0
 -0.240253  -0.240253   1.0          -0.0       -0.0       -0.0
 -0.240253  -0.240253  -0.240253     -0.0       -0.0       -0.0
 -0.240253  -0.240253  -0.240253     -0.0       -0.0       -0.0
 -0.0       -0.0       -0.0       …  -0.0       -0.0       -0.0
 -0.0       -0.0       -0.0          -0.0       -0.0       -0.0
 -0.0       -0.0       -0.0          -0.0       -0.0       -0.0
 -0.0       -0.0       -0.0          -0.0       -0.0       -0.240253
 -0.0       -0.0       -0.0          -0.0       -0.0       -0.0
 -0.0       -0.0       -0.0       …  -0.240253  -0.240253  -0.0
 -0.0       -0.0       -0.0          -0.240253  -0.240253  -0.240253
 -0.0       -0.0       -0.0          -0.240253  -0.240253  -0.0
 -0.0       -0.0       -0.0           1.0       -0.240253  -0.0
 -0.0       -0.0       -0.0          -0.240253   1.0       -0.0
 -

In [12]:
# then inverse A_2 to find x^*
A_2_inv = inv(A_2)


16×16 Matrix{Float64}:
 -1.87416e15  -1.61249e15  -1.61249e15  …  -1.61249e15  -1.35082e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15  …  -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.87416e15  -1.61249e15  -1.61249e15     -1.61249e15  -1.35082e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15  …  -1.38736e15  -1.16222e15
 -1.87416e15  -1.61249e15  -1.61249e15     -1.61249e15  -1.35082e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15  -1.38736e15     -1.38736e15  -1.16222e15
 -1.61249e15  -1.38736e15

In [20]:
# trying smaller beta
E_beta_3 = 0.1
E_beta_3_G = E_beta_3 * G
A_3 = I - E_beta_3_G
# then inverse A_3 to find x^*
A_3_inv = inv(A_3)

16×16 Matrix{Float64}:
 1.07222     0.153175     0.153175     …  0.00165979   0.00165979   0.109546
 0.153175    1.06084      0.151752        0.000237113  0.000237113  0.0156495
 0.153175    0.151752     1.06084         0.000237113  0.000237113  0.0156495
 0.153175    0.151752     0.151752        0.000237113  0.000237113  0.0156495
 0.153175    0.151752     0.151752        0.000237113  0.000237113  0.0156495
 0.00165979  0.000237113  0.000237113  …  0.000237113  0.000237113  0.0156495
 0.00165979  0.000237113  0.000237113     0.000237113  0.000237113  0.0156495
 0.00165979  0.000237113  0.000237113     0.000237113  0.000237113  0.0156495
 0.0116185   0.00165979   0.00165979      0.00165979   0.00165979   0.109546
 0.00165979  0.000237113  0.000237113     0.000237113  0.000237113  0.0156495
 0.00165979  0.000237113  0.000237113  …  0.151752     0.151752     0.0156495
 0.0116185   0.00165979   0.00165979      0.153175     0.153175     0.109546
 0.00165979  0.000237113  0.000237113     0.

In [30]:
# trying more general beta
E_beta_4 =  0.2 * p + 0.1 * (1 - p)
E_beta_4_G = E_beta_4 * G
A_4 = I - E_beta_4_G
# then inverse A_4 to find x^*
A_4_inv = inv(A_4)
# then we can compute x^* = A^{-1} * 1
x_star_4 = A_4_inv * SymPy.ones(16, 1)

16×1 Matrix{Sym{PyCall.PyObject}}:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1.0*(-4.79999999999996e-14*p^15 - 5.6e-12*p^14 - 2.9446e-10*p^13 - 9.18022e-9*p^12 - 1.8750764e-7*p^11 - 2.609043624e-6*p^10 - 2.47585965e-5*p^9 - 0.00015329741922*p^8 - 0.00052706194464*p^7 - 0.00021556354248*p^6 + 0.005602093970396*p^5 + 0.0160983519631*p^4 - 0.01028065193276*p^3 - 0.0757372

In [31]:
# retrieve the three types of x^*
# x_star for group leader
x_star_4_leader = x_star_4[1]
# find its derivative respect to p 
x_star_4_leader_derivative = diff(x_star_4_leader, p)

                      /                        14             13               >
                  1.0*\- 7.19999999999994e-13*p   - 7.84e-11*p   - 3.82798e-9* >
------------------------------------------------------------------------------ >
          16               15               14                13               >
1.44e-14*p   + 1.6304e-12*p   + 8.1858e-11*p   + 2.368884e-9*p   + 4.2509038e- >
                                                                               >

>  12                 11                  10                   9               >
> p   - 1.1016264e-7*p   - 2.06258404e-6*p   - 2.609043624e-5*p  - 0.000222827 >
> ---------------------------------------------------------------------------- >
>    12                   11                    10                    9        >
> 8*p   + 4.560492192e-7*p   + 2.0093866452e-6*p   - 1.7678720004e-5*p  - 0.00 >
>                                                                              >

>       8                 

In [32]:
# testing with specific values
for test_p in [0.1, 0.5, 0.9]
    val = subs(x_star_4_leader_derivative, Dict(p => test_p))
    println("x_star for leader at p = $test_p : ", val)
end

x_star for leader at p = 0.1 : 1.62235838868662
x_star for leader at p = 0.5 : 3.35648089694706
x_star for leader at p = 0.9 : 10.7880884217437


In [33]:
# testing for group members
x_star_4_member = x_star_4[2]
# find its derivative respect to p
x_star_4_member_derivative = diff(x_star_4_member, p)
# testing with specific values
for test_p in [0.1, 0.5, 0.9]
    val = subs(x_star_4_member_derivative, Dict(p => test_p))
    println("x_star for member at p = $test_p : ", val)
end


x_star for member at p = 0.1 : 1.37614146213776
x_star for member at p = 0.5 : 2.87063457993486
x_star for member at p = 0.9 : 9.26668397562319


In [34]:
# testing for higher level government
x_star_4_government = x_star_4[16]
# find its derivative respect to p
x_star_4_government_derivative = diff(x_star_4_government, p)
# testing with specific values
for test_p in [0.1, 0.5, 0.9]
    val = subs(x_star_4_government_derivative, Dict(p => test_p))
    println("x_star for government at p = $test_p : ", val)
end

x_star for government at p = 0.1 : 1.12992453558889
x_star for government at p = 0.5 : 2.38478826292267
x_star for government at p = 0.9 : 7.74527952950268
